# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:

  pypi-upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        if [ -f pyproject.toml ]; then poetry install; fi
    - name: Build Cython Code
      run: |
        poetry build -f sdist
        poetry install
    - name: Test with unittest
      run: |
        poetry run python -m unittest
    - name: Build and Upload Python Package
      run: |
        poetry config repositories.test-pypi https://test.pypi.org/legacy/
        poetry config pypi-token.test-pypi ${{secrets.PYPI_TEST_TOKEN}}
        poetry publish --repository test-pypi
