# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  pypi-upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        if [ -f Pipfile ]; then pipenv install; fi
    - name: Build Cython Code
      run: |
        pipenv run make
    - name: Test with unittest
      run: |
        pipenv run python -m unittest
    - name: Build Pip Packge
      run: |
        pipenv run VERSION_SUFIX=${GITHUB_RUN_ID} python setup.py sdist bdist_wheel
    - name: Upload Pip Packge
      run: |
        pipenv run TWINE_USERNAME=${{secrets.PYPI_USER}} TWINE_PASSWORD=${{secrets.PYPI_TOKEN}} python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
